<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Pac_emp_exp_code extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pac_emp_exp_code_model');
    }
    function checkSession(){


  		if($this->session->userdata('userId')== null && $this->session->userdata('userId')== ''){
  			$this->logout();
  		}

  	}

  	function logout(){
  		$this->session->sess_destroy();
  		redirect('/login/', 'refresh');
  	}


    /*
     * Listing of pac_emp_exp_code
     */
    function index()
    {
      if(!$this->User_model->isSysAdmin())
  			$this->logout();
        $data['pac_emp_exp_code'] = $this->Pac_emp_exp_code_model->get_all_pac_emp_exp_code();
	$data['title'] = 'PAC PR System - Admin';

        $data['content'] = $this->load->view('pac_emp_exp_code/index',$data,true);
        $this->load->view('template_view_admin',$data);
    }

    /*
     * Adding a new pac_emp_exp_code
     */
    function add()
    {
		if(!$this->User_model->isSysAdmin())
			$this->logout();
		
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
				'codename' => $this->input->post('codename'),
            );

            $pac_emp_exp_code_id = $this->Pac_emp_exp_code_model->add_pac_emp_exp_code($params);
            redirect('pac_emp_exp_code/index');
        }
        else
        {	$data['title'] = 'PAC PR System - Admin';
			$data['content'] = $this->load->view('pac_emp_exp_code/add',$data, true);
			$this->load->view('template_view_admin',$data);
			
        }
    }

    /*
     * Editing a pac_emp_exp_code
     */
    function edit($id)
    {
      if(!$this->User_model->isSysAdmin())
  			$this->logout();
        // check if the pac_emp_exp_code exists before trying to edit it
        $pac_emp_exp_code = $this->Pac_emp_exp_code_model->get_pac_emp_exp_code($id);

        if(isset($pac_emp_exp_code['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
					'codename' => $this->input->post('codename'),
                );

                $this->Pac_emp_exp_code_model->update_pac_emp_exp_code($id,$params);
                redirect('pac_emp_exp_code/index');
            }
            else
            {
                $data['pac_emp_exp_code'] = $this->Pac_emp_exp_code_model->get_pac_emp_exp_code($id);

                
                $data['title'] = 'PAC PR System - Admin';
        				$data['content'] = $this->load->view('pac_emp_exp_code/edit',$data,true);
        				$this->load->view('template_view_admin',$data);
            }
        }
        else
            show_error('The pac_emp_exp_code you are trying to edit does not exist.');
    }

    /*
     * Deleting pac_emp_exp_code
     */
    function remove($id)
    {
        $pac_emp_exp_code = $this->Pac_emp_exp_code_model->get_pac_emp_exp_code($id);

        // check if the pac_emp_exp_code exists before trying to delete it
        if(isset($pac_emp_exp_code['id']))
        {
            $this->Pac_emp_exp_code_model->delete_pac_emp_exp_code($id);
            redirect('pac_emp_exp_code/index');
        }
        else
            show_error('The pac_emp_exp_code you are trying to delete does not exist.');
    }

}
