<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Pac_employee extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pac_employee_model');
    }
    function checkSession(){


  		if($this->session->userdata('userId')== null && $this->session->userdata('userId')== ''){
  			$this->logout();
  		}

  	}

  	function logout(){
  		$this->session->sess_destroy();
  		redirect('/login/', 'refresh');
  	}

    /*
     * Listing of pac_employees
     */
    function index()
    {
      if(!$this->User_model->isSysAdmin())
  			$this->logout();

        $data['pac_employees'] = $this->Pac_employee_model->get_all_pac_employees();
        $data['title'] = 'PAC PR System - Admin';
        $data['content'] = $this->load->view('pac_employee/index',$data,true);
        $this->load->view('template_view_admin',$data);
    }

    /*
     * Adding a new pac_employee
     */
    function add()
    {	
		if(!$this->User_model->isSysAdmin())
  			$this->logout();
		
        $this->load->library('form_validation');

		$this->form_validation->set_rules('emp_firstname','Emp Firstname','required|max_length[50]');
		$this->form_validation->set_rules('emp_lastname','Emp Lastname','required|max_length[50]');
		$this->form_validation->set_rules('emp_email','Emp Email','required|max_length[50]|valid_email');
		$this->form_validation->set_rules('emp_role_id','Emp Role Id','required|integer');
		$this->form_validation->set_rules('exp_code_id','Exp Code Id','integer');
		$this->form_validation->set_rules('emp_status','Emp Status','required|max_length[10]');
		$this->form_validation->set_rules('emp_username','Emp Username','max_length[100]');
		$this->form_validation->set_rules('emp_password','Emp Password','max_length[255]');

		if($this->form_validation->run())
        {
            $params = array(
				'emp_firstname' => $this->input->post('emp_firstname'),
				'emp_lastname' => $this->input->post('emp_lastname'),
				'emp_email' => $this->input->post('emp_email'),
				'emp_role_id' => $this->input->post('emp_role_id'),
				'exp_code_id' => $this->input->post('exp_code_id'),
				'emp_status' => $this->input->post('emp_status'),
				'emp_username' => $this->input->post('emp_username'),
				'emp_password' => $this->encrypt->encode($this->input->post('emp_password')),
            );

            $pac_employee_id = $this->Pac_employee_model->add_pac_employee($params);
            redirect('pac_employee/index');
        }
        else
        {

			$this->load->model('Pac_emp_role_model');
			$this->load->model('Pac_emp_exp_code_model');
			
			$data['all_pac_emp_roles'] = $this->Pac_emp_role_model->get_all_pac_emp_roles();
			$data['all_pac_emp_exp_codes'] = $this->Pac_emp_exp_code_model->get_all_pac_emp_exp_code();

			$data['title'] = 'PAC PR System - Admin';
			$data['content'] = $this->load->view('pac_employee/add',$data,true);
			$this->load->view('template_view_admin',$data);
            
        }
    }

    /*
     * Editing a pac_employee
     */
    function edit($id)
    {
      if(!$this->User_model->isSysAdmin())
  			$this->logout();
        // check if the pac_employee exists before trying to edit it
        $pac_employee = $this->Pac_employee_model->get_pac_employee($id);

        if(isset($pac_employee['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('emp_firstname','Emp Firstname','required|max_length[50]');
			$this->form_validation->set_rules('emp_lastname','Emp Lastname','required|max_length[50]');
			$this->form_validation->set_rules('emp_email','Emp Email','required|max_length[50]|valid_email');
			$this->form_validation->set_rules('emp_role_id','Emp Role Id','required|integer');
			$this->form_validation->set_rules('exp_code_id','Exp Code Id','integer');
			$this->form_validation->set_rules('emp_status','Emp Status','required|max_length[10]');
			$this->form_validation->set_rules('emp_username','Emp Username','max_length[100]');
			$this->form_validation->set_rules('emp_password','Emp Password','max_length[255]');

			if($this->form_validation->run())
            {
                $params = array(
					'emp_firstname' => $this->input->post('emp_firstname'),
					'emp_lastname' => $this->input->post('emp_lastname'),
					'emp_email' => $this->input->post('emp_email'),
					'emp_role_id' => $this->input->post('emp_role_id'),
					'exp_code_id' => $this->input->post('exp_code_id'),
					'emp_status' => $this->input->post('emp_status'),
					'emp_username' => $this->input->post('emp_username'),
					'emp_password' => $this->input->post('emp_password'),
                );

                $this->Pac_employee_model->update_pac_employee($id,$params);
                redirect('pac_employee/index');
            }
            else
            {
                $data['pac_employee'] = $this->Pac_employee_model->get_pac_employee($id);

				$this->load->model('Pac_emp_role_model');
				$this->load->model('Pac_emp_exp_code_model');
				$data['all_pac_emp_roles'] = $this->Pac_emp_role_model->get_all_pac_emp_roles();
				$data['all_pac_emp_exp_codes'] = $this->Pac_emp_exp_code_model->get_all_pac_emp_exp_code();


                $data['title'] = 'PAC PR System - Admin';
        				$data['content'] = $this->load->view('pac_employee/edit',$data,true);
        				$this->load->view('template_view_admin',$data);
            }
        }
        else
            show_error('The pac_employee you are trying to edit does not exist.');
    }

    /*
     * Deleting pac_employee
     */
    function remove($id)
    {
        $pac_employee = $this->Pac_employee_model->get_pac_employee($id);

        // check if the pac_employee exists before trying to delete it
        if(isset($pac_employee['id']))
        {
            $this->Pac_employee_model->delete_pac_employee($id);
            redirect('pac_employee/index');
        }
        else
            show_error('The pac_employee you are trying to delete does not exist.');
    }

}
