<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Pac_emp_role extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pac_emp_role_model');
    }

    /*
     * Listing of pac_emp_roles
     */

     function checkSession(){


   		if($this->session->userdata('userId')== null && $this->session->userdata('userId')== ''){
   			$this->logout();
   		}

   	}

   	function logout(){
   		$this->session->sess_destroy();
   		redirect('/login/', 'refresh');
   	}

    function index()
    {
      if(!$this->User_model->isApprover())
  			$this->logout();
        $data['pac_emp_roles'] = $this->Pac_emp_role_model->get_all_pac_emp_roles();
        $data['title'] = 'PAC PR System - Admin';
        $data['content'] = $this->load->view('pac_emp_role/index',$data,true);
        $this->load->view('template_view_ash',$data);
    }

    /*
     * Adding a new pac_emp_role
     */
    function add()
    {
      if(!$this->User_model->isApprover())
        $this->logout();

        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','max_length[40]');
		$this->form_validation->set_rules('role_status','Role Status','max_length[10]');

		if($this->form_validation->run())
        {
            $params = array(
				'name' => $this->input->post('name'),
				'role_status' => $this->input->post('role_status'),
            );

            $pac_emp_role_id = $this->Pac_emp_role_model->add_pac_emp_role($params);
            redirect('pac_emp_role/index');
        }
        else
        {
          $data['title'] = 'PAC PR System - Admin';
         $data['content'] = $this->load->view('pac_emp_role/add',$data,true);
         $this->load->view('template_view_ash',$data);
        }
    }

    /*
     * Editing a pac_emp_role
     */
    function edit($id)
    {
      if(!$this->User_model->isApprover())
        $this->logout();
        // check if the pac_emp_role exists before trying to edit it
        $pac_emp_role = $this->Pac_emp_role_model->get_pac_emp_role($id);

        if(isset($pac_emp_role['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','max_length[40]');
			$this->form_validation->set_rules('role_status','Role Status','max_length[10]');

			if($this->form_validation->run())
            {
                $params = array(
					'name' => $this->input->post('name'),
					'role_status' => $this->input->post('role_status'),
                );

                $this->Pac_emp_role_model->update_pac_emp_role($id,$params);
                redirect('pac_emp_role/index');
            }
            else
            {
              	$this->load->model('Pac_emp_role_model');
                $data['pac_emp_role'] = $this->Pac_emp_role_model->get_pac_emp_role($id);
                $data['title'] = 'PAC PR System - Admin';
                $data['content'] = $this->load->view('pac_emp_role/edit',$data,true);
                $this->load->view('template_view_ash',$data);
            }
        }
        else
            show_error('The pac_emp_role you are trying to edit does not exist.');
    }

    /*
     * Deleting pac_emp_role
     */
    function remove($id)
    {
        $pac_emp_role = $this->Pac_emp_role_model->get_pac_emp_role($id);

        // check if the pac_emp_role exists before trying to delete it
        if(isset($pac_emp_role['id']))
        {
            $this->Pac_emp_role_model->delete_pac_emp_role($id);
            redirect('pac_emp_role/index');
        }
        else
            show_error('The pac_emp_role you are trying to delete does not exist.');
    }

}
