<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Pac_employee_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    function getdb(){
      if(ENVIRONMENT !== 'production')
        return $this->load->database('default',true);
      else
        return $this->load->database('production',true);
    }
    /*
     * Get pac_employee by id
     */
    function get_pac_employee($id)
    {
        $pac_employee = $this->getdb()->query("
            SELECT
                *

            FROM
                `pac_employees`

            WHERE
                `id` = ?
        ",array($id))->row_array();

        return $pac_employee;
    }

    /*
     * Get all pac_employees
     */
    function get_all_pac_employees()
    {
        $pac_employees = $this->getdb()->query("
            SELECT
                e.id, emp_firstname, emp_lastname, emp_email,
                a.name, b.codename,
                emp_status, emp_username, emp_password
            FROM
                `pac_employees` e,
                `pac_emp_roles` a,
                `pac_emp_exp_code` b

            WHERE
                1 = 1
                and e.emp_role_id = a.id
                and e.exp_code_id = b.id
        ")->result_array();

        return $pac_employees;
    }

    /*
     * function to add new pac_employee
     */
    function add_pac_employee($params)
    {
        $this->getdb()->insert('pac_employees',$params);
        return $this->getdb()->insert_id();
    }

    /*
     * function to update pac_employee
     */
    function update_pac_employee($id,$params)
    {
        $this->getdb()->where('id',$id);
        $response = $this->getdb()->update('pac_employees',$params,"id ='".$id."'");
        if($response)
        {
            return "pac_employee updated successfully";
        }
        else
        {
            return "Error occuring while updating pac_employee";
        }
    }

    /*
     * function to delete pac_employee
     */
    function delete_pac_employee($id)
    {
        $response = $this->getdb()->delete('pac_employees',array('id'=>$id));
        if($response)
        {
            return "pac_employee deleted successfully";
        }
        else
        {
            return "Error occuring while deleting pac_employee";
        }
    }
}
